### ISSUE TITLE
Screen flickering in IE 11

### ISSUE THREAD

**Issue by aothms** [xeolabs/xeoengine#105]
##### Description of the problem 

Not sure if this is due to my specific hardware / software, but I get horrible screen flickering on IE 11. I've found similar issues pertaining to other webgl libs, i.e. [1]. Solution is to set `preserveDrawingBuffer` to `true` during the context initialization.

[1] http://stackoverflow.com/questions/29074863/three-js-internet-explorer-11-flickering

##### xeoEngine version

- [ ] Dev
- [ ] Master
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Fixed - https://github.com/xeolabs/xeoengine/commit/42938ed499aca26a9358c8be652dd0925bc92db9
