### ISSUE TITLE
XEO.Group Feels Too Lightweight

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#17]
I'm a big fan of lightweight libraries. But XEO.Group feels too lightweight.  I miss being able to add objects to other objects and operate on them all as a whole. I'm not proposing GameObject.addGameObject in the primary library necessarily - but maybe some additional class like GroupableGameObject.addGameObject.

**Comment by xeolabs** [comment]
Agreed, an object hierarchy with state inheritance would be awesome, but at this stage I think it's a bit too hard to implement. XEO's policy is to fire a change event for almost **every** property that gets updated on a component, partly with a view to making it work as a backend/model for a node-based graphical scene builder. If you threw an object hierarchy into the mix, with state inheritance, you'd end up with a lot of event plumbing to implement within that hierarchy, so I put in the too-hard basket at this stage. Would be nice to have at some point though. I think the API can allow it one day without any (or much) backwards compatibility breakage.

BTW the XEO.Group is intentionally lightweight - it's just a basic collection class, which can contain any type of Component. Note that you can also put components into more than one Group. My intention with Group is to (in an application's code) do things like have a "selected" Group, a "highlighted" Group, maybe a "transparent" Group, and so on, where the same components could exist within multiple Groups. It's really a helper for the app-layer.

**Comment by xeolabs** [comment]
BTW, working on another engine, in that project we identified the need to have many different types of hierarchy, ie. "transformation", "ontology", "spatial" etc. So having a flat soup of Entities might be a good move in that respect, where potentially there would be a separate node graph for each different type of hierarchy, with nodes in those hierarchies having references to the Entities. If that makes sense.
