### ISSUE TITLE
Incorporate Constructive Solid Geometry Example

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#18]
Create an example to showcase constructive solid geometry
https://evanw.github.io/csg.js
https://en.wikipedia.org/wiki/Constructive_solid_geometry

**Comment by philmaker1** [comment]
I added a very basic example to JSFiddle relating to constructive solid geometry. This example is still using GameObject and has not yet been updated to XEO.Entity.

https://jsfiddle.net/philmaker/0e3hw1d4/

**Comment by xeolabs** [comment]
I've added your CSG example to the core examples collection, thanks: http://xeoengine.org/examples/#geometry_csg_example1
