### ISSUE TITLE
Consider Renaming XEO.GameObject

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#19]
Perhaps GameObject has market potential - but I prefer one word. What's an alternative to Entity?

**Comment by xeolabs** [comment]
Yes I would much prefer something else. Ideally, I would go for **XEO.Object**, however I couldn't get YUIDoc to document that class name while using the XEO namespace - [I posted a question on StackOverflow]( http://stackoverflow.com/q/33617362/572036?stw=2), so it might just be impossible to use the name XEO.Object alongside YUIDoc. 

Even though XEO is not really an entity-component system, perhaps "Entity" is the best option?

BTW GooEngine has an Entity class, while not being a real entity-component architecture.

**Comment by xeolabs** [comment]
PS. if anyone has a workaround for the [YUIDoc issue](http://stackoverflow.com/q/33617362/572036?stw=2) then I'll rename XEO.GameObject to **XEO.Object**, otherwise I'll probably rename it to **XEO.Entity**.

**Comment by philmaker1** [comment]
I don't have a workaround for YUIDoc. There's an entry on Wikipedia for
entry component systems. The A-Frame project uses entity component
terminology. And even though the word Entity seems MS-esque to me, it seems
like the best choice.

**Comment by xeolabs** [comment]
A heads-up - I'm in the process of renaming "GameObject" to "Entity", so that will appear in my next commit.

**Comment by xeolabs** [comment]
Done - reamed to "Entity" in source code, examples, docs and snapshot binaries.
