### ISSUE TITLE
Alternatives to Passing Scenes to Components?

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#21]
I understand how to construct components with the default XEO.scene. However when I create a new scene or additional scenes, why is it necessary to pass the scene to every new component I create? Is there some other alternative?

**Comment by xeolabs** [comment]
No alternative at the moment - note that passing a Scene into each component's constructor allows us to create components within multiple scenes, ie.,

````var scene1 = new XEO.Scene(..);
var scene2 = new XEO.Scene(..);
var object1 = new GameObject(scene1, ...);
var object2 = new GameObject(scene2, ...);
````

and of course you can create a component within the default ````XEO.scene```` if you omit that scene argument.

Offhand, I can't think of an alternative to specifying a non-default Scene in the constructor, short of having a "currently active" Scene, but that might cause some ambiguity with the default Scene..

**Comment by philmaker1** [comment]
Would it be possible to clone a component and reassign from one scene to another? My goal is to avoid needing to specify the scene for each and every component.

**Comment by xeolabs** [comment]
Still working on the exact semantics, but I'm thinking of having a factory method that looks like this:
````javascript
var childComponent = myParentComponent.getComponent(
    XEO.PhongMaterial, { diffuse [1,0,0] });
````
This method will create a component of the given type, whose lifecycle will be managed by ````myParentComponent````, where when ````myParentComponent```` is destroyed, the component will be destroyed also. The component will also be created within the same ````Scene```` as ````myParentComponent````, and ````myParentComponent```` itself can be a ````Scene````.

Also, you can optionally pass a "share ID" to the method, like this (see third argument):
````javascript
var myChildComponent = myParentComponent.getComponent(
    XEO.PhongMaterial, { diffuse [1,0,0] }, "myPhongMaterial");
````
If this method has already been called on ````myParentComponent```` (or some other component within the same ````Scene````), for the same component type and share ID, then the configs param (the third argument) is ignored, and the method returns the instance that was created previously.

You can then call
````javascript
myParentComponent.putComponent(myChildComponent);
````
to "release" the component, and when the number of calls for ````putComponent```` is the same as the number of ````getComponent```` calls, the component will be destroyed.

**Comment by xeolabs** [comment]
Not sure if this is exactly the solution required, but might help. I created this [new factory method](https://github.com/xeolabs/xeoengine/blob/master/src/component.js#L739) to create components whose lifecycles are managed by "owner" components, so that they are automatically destroyed when the owner is destroyed. The components also inherit the same Scene as the owner, and that method can be called on the Scene. It's used in components like XEO Skybox now, [see here](https://github.com/xeolabs/xeoengine/blob/master/src/skyboxes/skybox.js#L84).
