### ISSUE TITLE
Duplicate Indices Member in BoxGeometry

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#27]
https://github.com/xeolabs/xeoengine/blob/master/src/geometry/boxGeometry.js#L218

Really small issue - just something I noticed. This project is wicked awesome. I am a cheerleader.

**Comment by xeolabs** [comment]
Fixed - https://github.com/xeolabs/xeoengine/commit/6d043f5a9d5d217d4670965d991c6da8bd168ec4 - cheers.
