### ISSUE TITLE
Using CameraControl with a Scene

### ISSUE THREAD

**Issue by quaxquax** [xeolabs/xeoengine#34]
Not sure if I am just missing something, but whenever I am trying to add a CameraControl to the camera of my scene, the code stops working.

Tried referencing the scene's default camera directly, or using {camera: null} so that it would default to the parent scene's camera (as described in the API) - alas to no avail.

I altered one of your examples in this fiddle, and at the end try to add the CameraControl (currently commented out). Where am I going wrong? or did I stumble onto a bug?

https://jsfiddle.net/quaxquax/pb2Ls5s2/

**Comment by xeolabs** [comment]
Yes it's a bug all right, nothing wrong with your code - I'm seeing an error in the console which looks easy enough to fix. Got a flu at the moment, so will need to fix this one on the weekend - cheers

**Comment by quaxquax** [comment]
Hope the flu won't keep you down for long. Get better soon!

**Comment by xeolabs** [comment]
Thanks - back in action! This bug now fixed by commit https://github.com/xeolabs/xeoengine/commit/611b8a9471df2d5d6b003fbe7dac1a7681787b26 - fiddle works now.

**Comment by quaxquax** [comment]
Awesome, works like a charm now.
