### ISSUE TITLE
Investigate missing front faces in CX-20's example

### ISSUE THREAD

**Issue by xeolabs** [xeolabs/xeoengine#64]
Investigate missing frontfaces in http://jsdo.it/cx20/ApVP

**Comment by cx20** [comment]
xeoengine.min.js v0.1.0 (Built on 2015-09-24) 
![image](https://cloud.githubusercontent.com/assets/1833979/13556115/2d87ba64-e415-11e5-9d29-2c2084000c14.png)

xeoengine.min.js v0.1.0 (Built on 2016-03-04)
![image](https://cloud.githubusercontent.com/assets/1833979/13556117/35a2ad76-e415-11e5-87eb-5ba8b170471b.png)

**Comment by cx20** [comment]
I tried the code below.

```javascript
var modes = new XEO.Modes(object.scene);
object.modes = modes;
modes.backfaces = true;
```

I was able to revise a problem :)
However, I do not know whether it was a right way :(

Please tell me the correct use of the library.

**Comment by xeolabs** [comment]
Try this geometry - here's a [gist of a XEO.Geometry](https://gist.github.com/xeolabs/6975d70bcf9bb6cd21ad) that works OK. That's the same array structure as used for the SceneJS example.

In xeoEngine, backfaces are hidden by default, and the vertex winding order for frontfaces is counter-clockwise. So the geometry arrays in that gist will work with those defaults.

In the meantime, I'm going to try to find why the array layouts you were using before don't work for xeoEngine. It's strange, I'm not sure why. Since they are the same as you've used for BabylongJS, it would be good to be able to use those for xeoEngine also.

**Comment by cx20** [comment]
Thank you for advice :)

I understood  the same array structure as used for the SceneJS example worked correctly.
However, I want to use the same layout because I want to do the comparison with following samples.

> A Comparison of WebGL Libraries in the World through Displaying Basic Primitives.
> http://qiita.com/cx20/items/0fa19c96aa6470d98807

The array layout uses a thing same as the basically following sample.
(But the scale of the vertex array changes 1.0 to 0.5.)

> WebGL Lesson 4 – some real 3D objects | Learning WebGL.html
> http://learningwebgl.com/blog/?p=370

I modified it once so that a sample worked.
> http://jsdo.it/cx20/ApVP
> http://jsdo.it/cx20/cwdH
```javascript
modes.backfaces = true;
```

Please tell me if you have discovered something.

Thanks.

**Comment by xeolabs** [comment]
I'll have to work on this issue in about two weeks - I'll come back to it then.

**Comment by cx20** [comment]
> The array layout uses a thing same as the basically following sample.
> > WebGL Lesson 4 – some real 3D objects | Learning WebGL.html

I'm sorry. The layout was not same when I reconfirmed.

The backfaces flag was unnecessary when I made a layout the same.

````javascript
modes.backfaces = true;
````

The below are Buffer View of WebGL Inspector.

- Before

![000](https://cloud.githubusercontent.com/assets/1833979/13913307/b1202bd0-ef88-11e5-943d-8b86645c5e5b.gif)

http://jsdo.it/cx20/ApVP

- After

![001](https://cloud.githubusercontent.com/assets/1833979/13913309/b6259de0-ef88-11e5-8593-1b9d466125cf.gif)

http://jsdo.it/cx20/2cvR

**Comment by xeolabs** [comment]
Oh cool, so no bug?

**Comment by cx20** [comment]
Yes. I think that it is not a bug.

This is a problem of the culling.

![image](https://cloud.githubusercontent.com/assets/1833979/13915533/aad7ee06-ef98-11e5-802c-59116e1e5814.png)

Maybe, in the previous version  (Built on 2015-09-24) , I think the back side of the polygon was displayed.

I think that it is correct that the back side of the polygon is not displayed by default.

**Comment by xeolabs** [comment]
Excellent, thanks.
