### ISSUE TITLE
DIfference between xeoEngine and SceneJS?

### ISSUE THREAD

**Issue by trusktr-goin** [xeolabs/xeoengine#69]
What's the difference? Or does xeoEngine just build on top of SceneJS? If it builds on top, what does it add?

**Comment by xeolabs** [comment]
It's a completely different engine than SceneJS, not built on top. I'll write a wiki page summarizing the differences soon.  

Briefly, the difference is mainly in the scene architecture where SceneJS is a scene graph relying on state inheritance, while xeoEngine is entity-component. 

To get an overview of the differences, read the API intros and features lists on both of those frameworks' project pages.
