### ISSUE TITLE
[glTF import] Support for glb

### ISSUE THREAD

**Issue by smalcom** [xeolabs/xeoengine#94]
Hi.
Will the xeoengine support an glTF-binary(glb ext.)?

**Comment by xeolabs** [comment]
Hi, yes it will, I'm planning to add that support some time over the next few weeks, not sure when exactly though.

**Comment by smalcom** [comment]
That's good.
Thank you.

**Comment by DavidBerger98** [comment]
Has this been implemented? I can't find a GLBModel in model.js.
